const airlines = [
	{ name: "American Airlines", iata: "AA", icao: "AAL" },
	{ name: "Delta Air Lines", iata: "DL", icao: "DAL" },
	{ name: "United Airlines", iata: "UA", icao: "UAL" },
	{ name: "Southwest Airlines", iata: "WN", icao: "SWA" },
	{ name: "Alaska Airlines", iata: "AS", icao: "ASA" },
	{ name: "JetBlue Airways", iata: "B6", icao: "JBU" },
	{ name: "Spirit Airlines", iata: "NK", icao: "NKS" },
	{ name: "Frontier Airlines", iata: "F9", icao: "FFT" },
	{ name: "Hawaiian Airlines", iata: "HA", icao: "HAL" },
	{ name: "WestJet", iata: "WS", icao: "WJA" },
	{ name: "Air Canada", iata: "AC", icao: "ACA" },
	{ name: "Ryanair", iata: "FR", icao: "RYR" },
	{ name: "easyJet", iata: "U2", icao: "EZY" },
	{ name: "Lufthansa", iata: "LH", icao: "DLH" },
	{ name: "Turkish Airlines", iata: "TK", icao: "THY" },
	{ name: "Air France", iata: "AF", icao: "AFR" },
	{ name: "British Airways", iata: "BA", icao: "BAW" },
	{ name: "Emirates", iata: "EK", icao: "UAE" },
	{ name: "Qatar Airways", iata: "QR", icao: "QTR" },
	{ name: "KLM Royal Dutch Airlines", iata: "KL", icao: "KLM" },
	{ name: "Cathay Pacific", iata: "CX", icao: "CPA" },
	{ name: "Singapore Airlines", iata: "SQ", icao: "SIA" },
	{ name: "ANA All Nippon Airways", iata: "NH", icao: "ANA" },
	{ name: "Japan Airlines", iata: "JL", icao: "JAL" },
	{ name: "Aeroflot", iata: "SU", icao: "AFL" },
	{ name: "Qantas", iata: "QF", icao: "QFA" },
	{ name: "Etihad Airways", iata: "EY", icao: "ETD" },
	{ name: "EVA Air", iata: "BR", icao: "EVA" },
	{ name: "Korean Air", iata: "KE", icao: "KAL" },
	{ name: "Asiana Airlines", iata: "OZ", icao: "AAR" }
  ];
  
  module.exports = airlines;
  