const airports = [
	{ name: "Hartsfield-Jackson Atlanta International Airport", iata: "ATL", icao: "KATL", country: "USA" },
	{ name: "Beijing Capital International Airport", iata: "PEK", icao: "ZBAA", country: "China" },
	{ name: "Los Angeles International Airport", iata: "LAX", icao: "KLAX", country: "USA" },
	{ name: "Tokyo Haneda Airport", iata: "HND", icao: "RJTT", country: "Japan" },
	{ name: "Dubai International Airport", iata: "DXB", icao: "OMDB", country: "United Arab Emirates" },
	{ name: "O'Hare International Airport", iata: "ORD", icao: "KORD", country: "USA" },
	{ name: "London Heathrow Airport", iata: "LHR", icao: "EGLL", country: "United Kingdom" },
	{ name: "Hong Kong International Airport", iata: "HKG", icao: "VHHH", country: "China" },
	{ name: "Shanghai Pudong International Airport", iata: "PVG", icao: "ZSPD", country: "China" },
	{ name: "Charles de Gaulle Airport", iata: "CDG", icao: "LFPG", country: "France" },
	{ name: "Dallas/Fort Worth International Airport", iata: "DFW", icao: "KDFW", country: "USA" },
	{ name: "Guangzhou Baiyun International Airport", iata: "CAN", icao: "ZGGG", country: "China" },
	{ name: "Frankfurt Airport", iata: "FRA", icao: "EDDF", country: "Germany" },
	{ name: "Istanbul Airport", iata: "IST", icao: "LTFM", country: "Turkey" },
	{ name: "Singapore Changi Airport", iata: "SIN", icao: "WSSS", country: "Singapore" },
	{ name: "Incheon International Airport", iata: "ICN", icao: "RKSI", country: "South Korea" },
	{ name: "Denver International Airport", iata: "DEN", icao: "KDEN", country: "USA" },
	{ name: "Soekarno-Hatta International Airport", iata: "CGK", icao: "WIII", country: "Indonesia" },
	{ name: "Kuala Lumpur International Airport", iata: "KUL", icao: "WMKK", country: "Malaysia" },
	{ name: "Sydney Kingsford Smith Airport", iata: "SYD", icao: "YSSY", country: "Australia" },
	{ name: "Toronto Pearson International Airport", iata: "YYZ", icao: "CYYZ", country: "Canada" },
	{ name: "Madrid-Barajas Adolfo Suárez Airport", iata: "MAD", icao: "LEMD", country: "Spain" },
	{ name: "San Francisco International Airport", iata: "SFO", icao: "KSFO", country: "USA" },
	{ name: "Chengdu Shuangliu International Airport", iata: "CTU", icao: "ZUUU", country: "China" },
	{ name: "Seattle-Tacoma International Airport", iata: "SEA", icao: "KSEA", country: "USA" },
	{ name: "Miami International Airport", iata: "MIA", icao: "KMIA", country: "USA" },
	{ name: "George Bush Intercontinental Airport", iata: "IAH", icao: "KIAH", country: "USA" },
	{ name: "Phoenix Sky Harbor International Airport", iata: "PHX", icao: "KPHX", country: "USA" },
	{ name: "Charlotte Douglas International Airport", iata: "CLT", icao: "KCLT", country: "USA" },
	{ name: "Orlando International Airport", iata: "MCO", icao: "KMCO", country: "USA" },
	{ name: "Boston Logan International Airport", iata: "BOS", icao: "KBOS", country: "USA" },
	{ name: "McCarran International Airport", iata: "LAS", icao: "KLAS", country: "USA" },
	{ name: "Newark Liberty International Airport", iata: "EWR", icao: "KEWR", country: "USA" },
	{ name: "Minneapolis-Saint Paul International Airport", iata: "MSP", icao: "KMSP", country: "USA" },
	{ name: "Detroit Metropolitan Wayne County Airport", iata: "DTW", icao: "KDTW", country: "USA" },
	{ name: "Philadelphia International Airport", iata: "PHL", icao: "KPHL", country: "USA" },
	{ name: "Fort Lauderdale-Hollywood International Airport", iata: "FLL", icao: "KFLL", country: "USA" },
	{ name: "Salt Lake City International Airport", iata: "SLC", icao: "KSLC", country: "USA" },
	{ name: "Washington Dulles International Airport", iata: "IAD", icao: "KIAD", country: "USA" },
	{ name: "Houston William P. Hobby Airport", iata: "HOU", icao: "KHOU", country: "USA" },
	{ name: "Barcelona El Prat Airport", iata: "BCN", icao: "LEBL", country: "Spain" },
	{ name: "Vancouver International Airport", iata: "YVR", icao: "CYVR", country: "Canada" },
	{ name: "Gatwick Airport", iata: "LGW", icao: "EGKK", country: "United Kingdom" },
	{ name: "Benito Juárez International Airport", iata: "MEX", icao: "MMMX", country: "Mexico" },
	{ name: "São Paulo-Guarulhos International Airport", iata: "GRU", icao: "SBGR", country: "Brazil" },
	{ name: "Chicago Midway International Airport", iata: "MDW", icao: "KMDW", country: "USA" },
	{ name: "Paris Orly Airport", iata: "ORY", icao: "LFPO", country: "France" },
	{ name: "Dublin Airport", iata: "DUB", icao: "EIDW", country: "Ireland" },
	{ name: "Munich Airport", iata: "MUC", icao: "EDDM", country: "Germany" },
	{ name: "Rome Fiumicino Airport", iata: "FCO", icao: "LIRF", country: "Italy" }
];

module.exports = airports;
