const airports = [
	{ name: "Hartsfield-Jackson Atlanta International Airport", iata: "ATL", icao: "KATL", city: "Atlanta" },
	{ name: "Beijing Capital International Airport", iata: "PEK", icao: "ZBAA", city: "Beijing" },
	{ name: "Los Angeles International Airport", iata: "LAX", icao: "KLAX", city: "Los Angeles" },
	{ name: "Tokyo Haneda Airport", iata: "HND", icao: "RJTT", city: "Tokyo" },
	{ name: "Dubai International Airport", iata: "DXB", icao: "OMDB", city: "Dubai" },
	{ name: "O'Hare International Airport", iata: "ORD", icao: "KORD", city: "Chicago" },
	{ name: "London Heathrow Airport", iata: "LHR", icao: "EGLL", city: "London" },
	{ name: "Hong Kong International Airport", iata: "HKG", icao: "VHHH", city: "Hong Kong" },
	{ name: "Shanghai Pudong International Airport", iata: "PVG", icao: "ZSPD", city: "Shanghai" },
	{ name: "Charles de Gaulle Airport", iata: "CDG", icao: "LFPG", city: "Paris" },
	{ name: "Dallas/Fort Worth International Airport", iata: "DFW", icao: "KDFW", city: "Dallas/Fort Worth" },
	{ name: "Guangzhou Baiyun International Airport", iata: "CAN", icao: "ZGGG", city: "Guangzhou" },
	{ name: "Frankfurt Airport", iata: "FRA", icao: "EDDF", city: "Frankfurt" },
	{ name: "Istanbul Airport", iata: "IST", icao: "LTFM", city: "Istanbul" },
	{ name: "Singapore Changi Airport", iata: "SIN", icao: "WSSS", city: "Singapore" },
	{ name: "Incheon International Airport", iata: "ICN", icao: "RKSI", city: "Incheon" },
	{ name: "Denver International Airport", iata: "DEN", icao: "KDEN", city: "Denver" },
	{ name: "Soekarno-Hatta International Airport", iata: "CGK", icao: "WIII", city: "Jakarta" },
	{ name: "Kuala Lumpur International Airport", iata: "KUL", icao: "WMKK", city: "Kuala Lumpur" },
	{ name: "Sydney Kingsford Smith Airport", iata: "SYD", icao: "YSSY", city: "Sydney" },
	{ name: "Toronto Pearson International Airport", iata: "YYZ", icao: "CYYZ", city: "Toronto" },
	{ name: "Madrid-Barajas Adolfo Suárez Airport", iata: "MAD", icao: "LEMD", city: "Madrid" },
	{ name: "San Francisco International Airport", iata: "SFO", icao: "KSFO", city: "San Francisco" },
	{ name: "Chengdu Shuangliu International Airport", iata: "CTU", icao: "ZUUU", city: "Chengdu" },
	{ name: "Seattle-Tacoma International Airport", iata: "SEA", icao: "KSEA", city: "Seattle" },
	{ name: "Miami International Airport", iata: "MIA", icao: "KMIA", city: "Miami" },
	{ name: "George Bush Intercontinental Airport", iata: "IAH", icao: "KIAH", city: "Houston" },
	{ name: "Phoenix Sky Harbor International Airport", iata: "PHX", icao: "KPHX", city: "Phoenix" },
	{ name: "Charlotte Douglas International Airport", iata: "CLT", icao: "KCLT", city: "Charlotte" },
	{ name: "Orlando International Airport", iata: "MCO", icao: "KMCO", city: "Orlando" },
	{ name: "Boston Logan International Airport", iata: "BOS", icao: "KBOS", city: "Boston" },
	{ name: "McCarran International Airport", iata: "LAS", icao: "KLAS", city: "Las Vegas" },
	{ name: "Newark Liberty International Airport", iata: "EWR", icao: "KEWR", city: "Newark" },
	{ name: "Minneapolis-Saint Paul International Airport", iata: "MSP", icao: "KMSP", city: "Minneapolis-Saint Paul" },
	{ name: "Detroit Metropolitan Wayne County Airport", iata: "DTW", icao: "KDTW", city: "Detroit" },
	{ name: "Philadelphia International Airport", iata: "PHL", icao: "KPHL", city: "Philadelphia" },
	{ name: "Fort Lauderdale-Hollywood International Airport", iata: "FLL", icao: "KFLL", city: "Fort Lauderdale" },
	{ name: "Salt Lake City International Airport", iata: "SLC", icao: "KSLC", city: "Salt Lake City" },
	{ name: "Washington Dulles International Airport", iata: "IAD", icao: "KIAD", city: "Washington D.C." },
	{ name: "Houston William P. Hobby Airport", iata: "HOU", icao: "KHOU", city: "Houston" },
	{ name: "Barcelona El Prat Airport", iata: "BCN", icao: "LEBL", city: "Barcelona" },
	{ name: "Vancouver International Airport", iata: "YVR", icao: "CYVR", city: "Vancouver" },
	{ name: "Gatwick Airport", iata: "LGW", icao: "EGKK", city: "London" },
	{ name: "Benito Juárez International Airport", iata: "MEX", icao: "MMMX", city: "Mexico City" },
	{ name: "São Paulo-Guarulhos International Airport", iata: "GRU", icao: "SBGR", city: "São Paulo" },
	{ name: "Chicago Midway International Airport", iata: "MDW", icao: "KMDW", city: "Chicago" },
	{ name: "Paris Orly Airport", iata: "ORY", icao: "LFPO", city: "Paris" },
	{ name: "Dublin Airport", iata: "DUB", icao: "EIDW", city: "Dublin" },
	{ name: "Munich Airport", iata: "MUC", icao: "EDDM", city: "Munich" },
	{ name: "Rome Fiumicino Airport", iata: "FCO", icao: "LIRF", city: "Rome" }
];

module.exports = airports;
